export type UILang = "it" | "en" | "es" | "de"; // zh riservato
let current: UILang = "it";
export function setLang(l: UILang) { current = l; }
export function getLang(): UILang { return current; }
type Dict = Record<UILang, Record<string, string>>;
export const t: (k: string) => string = (k) => dict[current]?.[k] ?? dict.en?.[k] ?? k;

export const dict: Dict = {
  it: { app_name:"World", home_title:"Pronto a scoprire la città? 🚀", use_my_location:"Usa la mia posizione", select_city:"Seleziona città", tours:"Tours", community:"Community", profile:"Profilo", login:"Accedi", logout:"Esci", days:"Giorni", interests:"Interessi", generate:"Genera itinerario", choose_attractions:"Scegli attrazioni", schedule_notifications:"Pianifica promemoria", phrases:"Frasi utili", airport:"Aeroporto", hotel:"Albergo", restaurant:"Ristorante", transport:"Trasporti", shopping:"Shopping", emergency:"Emergenze", report:"Segnala", like:"Mi piace", comment:"Commenta", add_photo_video:"Aggiungi foto/video", post:"Pubblica", language:"Lingua", privacy:"Privacy", terms:"Termini d’uso" },
  en: { app_name:"World", home_title:"Ready to explore? 🚀", use_my_location:"Use my location", select_city:"Select city", tours:"Tours", community:"Community", profile:"Profile", login:"Login", logout:"Logout", days:"Days", interests:"Interests", generate:"Generate itinerary", choose_attractions:"Choose attractions", schedule_notifications:"Schedule reminders", phrases:"Useful phrases", airport:"Airport", hotel:"Hotel", restaurant:"Restaurant", transport:"Transport", shopping:"Shopping", emergency:"Emergency", report:"Report", like:"Like", comment:"Comment", add_photo_video:"Add photo/video", post:"Post", language:"Language", privacy:"Privacy", terms:"Terms of Use" },
  es: { app_name:"World", home_title:"¿Listo para explorar? 🚀", use_my_location:"Usar mi ubicación", select_city:"Seleccionar ciudad", tours:"Tours", community:"Comunidad", profile:"Perfil", login:"Iniciar sesión", logout:"Salir", days:"Días", interests:"Intereses", generate:"Generar itinerario", choose_attractions:"Elegir atracciones", schedule_notifications:"Programar recordatorios", phrases:"Frases útiles", airport:"Aeropuerto", hotel:"Hotel", restaurant:"Restaurante", transport:"Transporte", shopping:"Compras", emergency:"Emergencia", report:"Reportar", like:"Me gusta", comment:"Comentar", add_photo_video:"Añadir foto/vídeo", post:"Publicar", language:"Idioma", privacy:"Privacidad", terms:"Términos de uso" },
  de: { app_name:"World", home_title:"Bereit zu entdecken? 🚀", use_my_location:"Meinen Standort verwenden", select_city:"Stadt auswählen", tours:"Touren", community:"Community", profile:"Profil", login:"Anmelden", logout:"Abmelden", days:"Tage", interests:"Interessen", generate:"Reiseplan erstellen", choose_attractions:"Attraktionen wählen", schedule_notifications:"Erinnerungen planen", phrases:"Nützliche Sätze", airport:"Flughafen", hotel:"Hotel", restaurant:"Restaurant", transport:"Verkehr", shopping:"Einkaufen", emergency:"Notfall", report:"Melden", like:"Gefällt mir", comment:"Kommentieren", add_photo_video:"Foto/Video hinzufügen", post:"Posten", language:"Sprache", privacy:"Datenschutz", terms:"Nutzungsbedingungen" }
};
